accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^register/$', views.register, name="register"),
	url(r'^login/$', views.login_view, name="login"),
	url(r'^logout/$', views.logout_view, name="logout"),
]

homemaker/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from accounts.views import landing_page, home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', landing_page, name='landing-page'),
    url(r'^home/$', home, name='home'),
    url(r'^audiosystem/', include('audiosystem.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^mobile/', include('mobile.urls')),
    url(r'^television/', include('television.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mobile/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'mobile'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^contacts/$', views.contact_list, name='all-contacts'),
	url(r'^contacts/(?P<slug>[\w-]+)/$', views.custom_contact_list, name='custom-contacts'),
	url(r'^contact/add/$', views.add_contact, name='add-contact'),
	url(r'^contact/edit/(?P<slug>[\w-]+)/$', views.edit_contact, name='edit-contact'),
	url(r'^contact/delete/(?P<slug>[\w-]+)/$', views.DeleteContact.as_view(), name='delete-contact'),
	url(r'^contact/(?P<slug>[\w-]+)/$', views.contact_detail, name="contact"),
	url(r'^call/select-contact/$', views.call_select_contact, name="call-select-contact"),
	url(r'^call/(?P<slug>[\w-]+)/$', views.call, name="call"),
	url(r'^check-incoming-call-sms/$', views.incoming_call_sms_check, name='check-incoming-call-sms'),
	url(r'^receive_call/$', views.receive_call, name='receive-call'),
	url(r'^abort_call/$', views.abort_call, name='abort-call'),
	url(r'^check_call_connection/$', views.check_call_connection, name='check-call-connection'),
	url(r'^message/select-contact/$', views.message_select_contact, name="message-select-contact"),
	url(r'^message/(?P<slug>[\w-]+)/$', views.chatroom, name="message"),
	url(r'^send_sms/$', views.send_sms_ajax, name="send-sms"),
	url(r'^make-call/$', views.make_call, name='make-call'),
]

television/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'television'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^brands/$', views.brands, name='brands'),
	url(r'^(?P<slug>[\w-]+)/remote-models/$', views.remote_models,name='remote-models'),
	url(r'^remote/(?P<slug>[\w-]+)/$',views.remote_detail, name='remote-detail'),
	url(r'^remote/(?P<slug>[\w-]+)/add/$', views.add_remote, name='remote-add'),
	url(r'^remote/(?P<slug>[\w-]+)/operate/$', views.remote_area, name='remote-area'),
	url(r'^send-ir-code/$', views.sendIRdata, name='send-ir-code'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import FileExtensionValidator

# Create your models here.

class RPiUser(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	avatar = models.FileField(null=True, default='default_avatar.png', help_text="upload jpg, jpeg, png files only", validators=[FileExtensionValidator(['jpg','png','jpeg'])])
	mobile_no = models.CharField(max_length=13,default='', unique=True)
	slug = models.SlugField(unique=True, max_length=100)

	def get_absolute_url(self):
		return reverse()

	def __str__(self):
		return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import RPiUser

class UserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name','email', 'password1', 'password2',]

	def clean_email(self):
		if User.objects.filter(email__iexact=self.cleaned_data['email']):
			raise forms.ValidationError("Email id already exists")
		return self.cleaned_data['email']

class RPiUserForm(forms.ModelForm):
	class Meta:
		model = RPiUser
		fields = ['mobile_no', 'avatar',]

	def clean_mobile_no(self):
		if RPiUser.objects.filter(mobile_no__iexact=self.cleaned_data['mobile_no']):
			raise forms.ValidationError("Mobile number already exists")
		return self.cleaned_data['mobile_no']

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.contrib import messages
from django.urls import reverse
from django import forms
from .models import RPiUser
from .forms import UserForm, RPiUserForm
# Create your views here.

def landing_page(request):
	if request.user.is_authenticated:
		return redirect('home')
	return render(request, 'accounts/landing_page.html')

@login_required
def home(request):
	if request.user.is_authenticated:
		return render(request, 'accounts/home.html',{})
	else:
		return redirect('landing-page')

def login_view(request):
	if request.user.is_authenticated:
		return redirect('home')
	if request.method == 'POST':
	    username = request.POST['username']
	    password = request.POST['password']
	    user = authenticate(request, username=username, password=password)
	    if user is not None:
	        login(request, user)
	        return redirect('home')
	    else:
	    	messages.error(request, "Invalid username or password")
	form = AuthenticationForm()
	return render(request,'accounts/login.html', {'form' : form})

@login_required
def logout_view(request):
	if request.user.is_authenticated:
		logout(request)
		return render(request, 'accounts/logged_out.html',{})
	else:
		return redirect('landing-page')

def register(request):
	if request.method == 'POST':
		user_form = UserForm(request.POST,request.FILES)
		profile_form = RPiUserForm(request.POST,request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			new_user = user_form.save(commit=False)
			new_user.set_password(user_form.cleaned_data['password2'])
			new_user.save()
			profile=RPiUser.objects.create(user=new_user)
			profile.mobile_no = profile_form.cleaned_data['mobile_no']
			profile.slug = slugify(new_user.username)
			profile.avatar = profile_form.cleaned_data['avatar']
			profile.save()
			return redirect('accounts:login')
		else:
			messages.error(request, "Mobile number/E-mail already exists")
	else:
		user_form = UserForm()
		profile_form = RPiUserForm()
	return render(request, 'accounts/register.html', {'user_form':user_form, 'profile_form':profile_form})

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
                
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Merienda+One|Montserrat|PT+Sans|Sanchez" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/forms.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'audiosystem/css/audiobox.css' %}">
    </head>

    <body onload="call_voice()">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'landing-page' %}">Homemaker Assistance System</a>
                </div>

                <div class="collapse navbar-collapse" id="navBar">
                    <ul class="nav navbar-nav">
                        <li><i class="fa fa-microphone fa-3x menuMicorphone"></i></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="">Demo</a></li>
                        <li><a href="">Help</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <div class="panel">
                    <div class="panel-heading">      
                        <h3 class="text-center">{% block content_title %}{% endblock %}</h3>
                        <hr>
                    </div>
                    <div class="panel-body">
                        {% include 'accounts/messages.html' %}
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>

        <footer class="container-fluid">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-xs-12 footerMenu">
                        <h4 class="text-center"><b>Links</b></h4>
                        <ul>
                            <li>
                                <a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span>&nbsp; Home</a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-off"></span>&nbsp; Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>  
            </div>
        </footer>
        <script type="text/javascript" src="{% static 'audiosystem/js/tts.js' %}"></script>
        <script type="text/javascript" src="{% static 'audiosystem/js/ttsForm.js' %}"></script>
        <script type="text/javascript" src="{% static 'audiosystem/js/select_contacts.js' %}"></script>
        <script type="text/javascript" src="{% static 'audiosystem/js/confirmations.js' %}"></script>
        <script type="text/javascript" src="{% static 'mobile/js/keyboard.js' %}"></script>
        <script type="text/javascript" src="{% static 'mobile/js/call_sms.js' %}"></script>
        <script type="text/javascript">
            function call_voice(){
                check_incoming_call_sms();
                selectContacts();
                console.log("functions loaded");
            }
        </script>    </body>
</html>

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% load staticfiles %}

{% block title %}Homemaker Assistance System{% endblock %}

{% block content_title %}Welcome to Homemaker Assistance System{% endblock %}

{% block content %}
		<div class="audioContainer text-center">
			<i class="fa fa-microphone fa-5x microphone"></i>
		</div>
		<div class="row">
			<a href="{% url 'mobile:index' %}">
				<div class="col-sm-6 col-md-6 col-12">
					<div class="panel homePage" style="background-color: #FF5733;">
						<div class="panel-body">
							<span class="glyphicon glyphicon-phone"></span>&nbsp; Mobile
							<br>
							<b class="homeBig">Use your mobile</b>	
						</div>
					</div>
				</div>
			</a>
			<a href="{% url 'television:index' %}">
				<div class="col-sm-6 col-md-6 col-12">
					<div class="panel homePage" style="background-color: #900C3F;">
						<div class="panel-body">
							<i class="fa fa-television" aria-hidden="true"></i>&nbsp; Television
							<br>
							<b class="homeBig">Control your TV</b>
						</div>
					</div>
				</div>
			</a>
		</div>

{% endblock %}

accounts/templates/accounts/landing_page.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Homemaker Assistance System{% endblock %}

{% block content_title %}Welcome to Homemaker Assistance System{% endblock %}

{% block content %}

	<p><a href="{% url 'accounts:login' %}">Login</a> to make your life easier</p>

{% endblock %}

accounts/templates/accounts/logged_out.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Logged out{% endblock %}

{% block content_title %}Logged out{% endblock %}

{% block content %}
	<p><a href="{% url 'accounts:login' %}">Login</a> again</p>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Login{% endblock %}

{% block content_title %}Login{% endblock %}

{% block content %}
	{% include 'accounts/messages.html' %}
		<form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{% include 'accounts/form_template.html' %}
			<button type="submit" class="btn btn-success quarterWidth"><span class="glyphicon glyphicon-log-in"></span>&nbsp; Login</button>
		</form>
{% endblock %}

accounts/templates/accounts/profile_base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
                
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Merienda+One|Montserrat|PT+Sans|Sanchez" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/forms.css' %}">
    </head>

    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'landing-page' %}">Homemaker Assistance System</a>
                </div>

                <div class="collapse navbar-collapse" id="navBar">
                    <ul class="nav navbar-nav navbar">
                        <li><a href="">Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <div class="panel">
                    <div class="panel-heading">      
                        <h3 class="text-center">{% block content_title %}{% endblock %}</h3>
                        <hr>
                    </div>
                    <div class="panel-body">
                         {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
        
        <footer class="container-fluid">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-xs-12 footerMenu">
                        <h4 class="text-center"><b>Links</b></h4>
                        <ul>
                            <li>
                                <a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span>&nbsp; Home</a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span>&nbsp; Login</a>
                            </li>
                        </ul>
                    </div>
                </div>  
            </div>
        </footer>
    </body>
</html>

accounts/templates/accounts/profile_form_template.html
{% for field in user_form %}
 	<div class="form-group">
 		<div class="text-center">
	        {% for error in field.errors %}
	            <div class="alert alert-danger">
	                <strong>{{ error|escape }}</strong>
	            </div>
	        {% endfor %}
		</div>
		<label>{{ field.label_tag }}</label>
   		{{ field }}
    	{% if field.help_text %}<p class="help-block">{{ field.help_text }}</p>{% endif %}
	</div>
{% endfor %}

{% for field in profile_form %}
 	<div class="form-group">
 		<div class="text-center">
	        {% for error in field.errors %}
	            <div class="alert alert-danger">
	                <strong>{{ error|escape }}</strong>
	            </div>
	        {% endfor %}
		</div>
		<label>{{ field.label_tag }}</label>
   		{{ field }}
    	{% if field.help_text %}<p class="help-block">{{ field.help_text }}</p>{% endif %}
	</div>
{% endfor %}

accounts/templates/accounts/register.html
{% extends 'accounts/profile_base.html' %}

{% block title %}Register{% endblock %}

{% block content_title %}Register{% endblock %}

{% block content %}
	{% include 'accounts/messages.html' %}
		<form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{% include 'accounts/profile_form_template.html' %}
			<button type="submit" class="btn btn-success quarterWidth"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Register</button>
		</form>
{% endblock %}