homemaker/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from accounts.views import landing_page, home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', landing_page, name='landing-page'),
    url(r'^home/$', home, name='home'),
    url(r'^audiosystem/', include('audiosystem.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^mobile/', include('mobile.urls')),
    url(r'^television/', include('television.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mobile/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'mobile'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^contacts/$', views.contact_list, name='all-contacts'),
	url(r'^contacts/(?P<slug>[\w-]+)/$', views.custom_contact_list, name='custom-contacts'),
	url(r'^contact/add/$', views.add_contact, name='add-contact'),
	url(r'^contact/edit/(?P<slug>[\w-]+)/$', views.edit_contact, name='edit-contact'),
	url(r'^contact/delete/(?P<slug>[\w-]+)/$', views.DeleteContact.as_view(), name='delete-contact'),
	url(r'^contact/(?P<slug>[\w-]+)/$', views.contact_detail, name="contact"),
	url(r'^call/select-contact/$', views.call_select_contact, name="call-select-contact"),
	url(r'^call/(?P<slug>[\w-]+)/$', views.call, name="call"),
	url(r'^check-incoming-call-sms/$', views.incoming_call_sms_check, name='check-incoming-call-sms'),
	url(r'^receive_call/$', views.receive_call, name='receive-call'),
	url(r'^abort_call/$', views.abort_call, name='abort-call'),
	url(r'^check_call_connection/$', views.check_call_connection, name='check-call-connection'),
	url(r'^message/select-contact/$', views.message_select_contact, name="message-select-contact"),
	url(r'^message/(?P<slug>[\w-]+)/$', views.chatroom, name="message"),
	url(r'^send_sms/$', views.send_sms_ajax, name="send-sms"),
	url(r'^make-call/$', views.make_call, name='make-call'),
]

television/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'television'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^brands/$', views.brands, name='brands'),
	url(r'^(?P<slug>[\w-]+)/remote-models/$', views.remote_models,name='remote-models'),
	url(r'^remote/(?P<slug>[\w-]+)/$',views.remote_detail, name='remote-detail'),
	url(r'^remote/(?P<slug>[\w-]+)/add/$', views.add_remote, name='remote-add'),
	url(r'^remote/(?P<slug>[\w-]+)/operate/$', views.remote_area, name='remote-area'),
	url(r'^send-ir-code/$', views.sendIRdata, name='send-ir-code'),
]

television/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import FileExtensionValidator
from django.utils import timezone
import datetime

# Create your models here.

class Brand(models.Model):
	name = models.CharField(max_length=100, default='')
	slug = models.SlugField(unique=True, max_length=500)	#slug=name

	def __str__(self):
		return self.name

class Remote(models.Model):
	user = models.ManyToManyField(settings.AUTH_USER_MODEL)
	brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
	model = models.CharField(max_length=100, default='')
	description = models.TextField(default='')
	REMOTE_TYPES = (
		('t', 'television'),
		('s', 'setup-box'),
	)
	remote_type = models.CharField(max_length=1, default='s', choices=REMOTE_TYPES, blank=False, null=True)
	remotes_in_use = models.IntegerField(default=0)
	ir_code_file = models.FileField(null=True, help_text="upload .json files only", validators=[FileExtensionValidator(['json'])])
	slug = models.SlugField(unique=True, max_length=500)  #slug=brand-model

	def __str__(self):
		return str(self.brand) + "-" + self.model

television/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse,JsonResponse
from django.template import Template, Context, loader
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.utils.text import slugify
from django.db.models import Q
import json
import os
from .models import Brand, Remote
from .scripts import send_data

basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Create your views here.
@login_required
def index(request):
	remotes =Remote.objects.filter(user=request.user)
	return render(request, 'television/index.html', {'remotes':remotes})

@login_required
def brands(request):
	brands = Brand.objects.all()
	return render(request, 'television/brands.html', {'brands':brands})

@login_required
def remote_models(request,slug):
	brand = get_object_or_404(Brand, slug=slug)
	models = Remote.objects.filter(brand=brand)
	return render(request, 'television/remote_models.html', {'models':models,'brand':brand})

@login_required
def remote_detail(request,slug):
	remote = get_object_or_404(Remote, slug=slug)
	try:
		flag_remote = Remote.objects.get(user=request.user,slug=slug)
		if flag_remote:
			flag = 1
	except:
		flag = 0
	return render(request, 'television/remote_detail.html', {'remote':remote,'flag':flag})

@login_required
def add_remote(request, slug):
	remote = get_object_or_404(Remote, slug=slug)
	try:
		flag_remote = Remote.objects.get(user=request.user,slug=slug)
		if flag_remote:
			messages.info(request, "Remote already in your account")
	except Remote.DoesNotExist:
		remote.user.add(request.user)
		remote.remotes_in_use +=1
		remote.save()
		messages.success(request, "Remote added successfully to your account")
	return redirect('television:index')

@login_required
def remote_area(request, slug):
	remote = get_object_or_404(Remote, slug=slug)
	try:
		flag_remote = Remote.objects.get(user=request.user,slug=slug)
		if flag_remote:
			return render(request, 'television/remote_area.html', {'remote':remote})
	except:
		messages.error(request, 'No such remote exists in your account')
		return redirect('television:index')

@login_required
def sendIRdata(request):
	if request.method == 'POST':
		if request.is_ajax():
			button = request.POST.get('button')
			remoteSlug = request.POST.get('remoteSlug')
			remote = Remote.objects.get(user=request.user,slug=remoteSlug)
			with open(basedir+remote.ir_code_file.url) as jsonfile:
				jsonData = json.load(jsonfile)
			hexCode = jsonData[button]
			decimalCode = int(hexCode,16)
			print(decimalCode)
			send_data.irSend(str(decimalCode))
	return JsonResponse({
	    'success': True,
	})

television/templates/television/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
                
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Merienda+One|Montserrat|PT+Sans|Sanchez" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'television/css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'audiosystem/css/audiobox.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'television/css/forms.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'television/css/remote.css' %}">
    </head>

    <body onload="call_voice()">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">Homemaker Assistance System</a>
                </div>

                <div class="collapse navbar-collapse" id="navBar">
                    <ul class="nav navbar-nav">
                        <li><i class="fa fa-microphone fa-3x menuMicorphone"></i></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="">Demo</a></li>
                        <li><a href="">Help</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block breadcrumbs %}
            <div class="breadcrumbs">
                <a href="{% url 'home' %}">Home</a>
                {% block crumbs %}
                {% endblock %}
            </div>
        {% endblock %}

        <div class="container-fluid">
            <div class="row">
                <div class="panel">
                    <div class="panel-heading">      
                        <h3 class="text-center">{% block content_title %}{% endblock %}</h3>
                        <hr>
                    </div>
                    <div class="panel-body">
                         {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>

        <footer class="container-fluid">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-xs-12 footerMenu">
                        <h4 class="text-center"><b>Links</b></h4>
                        <ul>
                            <li>
                                <a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span>&nbsp; Home</a>
                            </li>
                        </ul>
                    </div>
                </div>  
            </div>
        </footer>
        <script type="text/javascript" src="{% static 'television/js/remote.js' %}"></script>
        <script type="text/javascript" src="{% static 'audiosystem/js/tts.js' %}"></script>
        <script type="text/javascript" src="{% static 'audiosystem/js/ttsForm.js' %}"></script>
        <script type="text/javascript" src="{% static 'audiosystem/js/select_contacts.js' %}"></script>
        <script type="text/javascript" src="{% static 'audiosystem/js/confirmations.js' %}"></script>
        <script type="text/javascript" src="{% static 'mobile/js/keyboard.js' %}"></script>
        <script type="text/javascript" src="{% static 'mobile/js/call_sms.js' %}"></script>
        <script type="text/javascript">
            function call_voice(){
                check_incoming_call_sms();
                startConverting();
                console.log("functions loaded");
            }
        </script>
    </body>
</html>

television/templates/television/brands.html
{% extends 'television/base.html' %}

{% block title %}Television Module{% endblock %}

{% block content_title %}Select Brands{% endblock %}

{% block voiceRecognizer %}onload="startConverting()"{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'television:index' %}">Television</a>
    &rsaquo; <a href="{% url 'television:brands' %}">Brands</a>
{% endblock %}

{% block content %}
	{% include 'television/messages.html' %}
	<div class="table-responsive">
		<table class="table table-striped" align="center">
			<thead>
				<tr>
					<th>Brand Name</th>
				</tr>	
			</thead>
				<tbody>
					{% for brand in brands %}
					<tbody>
						<tr>
							<td>
								<a href="{% url 'television:remote-models' slug=brand.slug %}">{{ brand.name }}</a>
							</td>
							<td>
								<a href="{% url 'television:remote-models' slug=brand.slug %}"><button class="btn btn-info btn-sm"><span class="glyphicon glyphicon-menu-right"></span>&nbsp; See remotes</button></a>
							</td>
						</tr>
					</tbody>
					{% endfor %}
				</tbody>
			</table>
		</div>
{% endblock %}

television/templates/television/index.html
{% extends 'television/base.html' %}

{% block title %}Television Module{% endblock %}

{% block content_title %}Remotes <a href="{% url 'television:brands' %}"><button class="btn btn-sm btn-success"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Add Remote</button></a>{% endblock %}

{% block voiceRecognizer %}onload="startConverting()"{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'television:index' %}">Television</a>
{% endblock %}

{% block content %}
	{% include 'television/messages.html' %}
	{% if remotes.count != 0 %}
		<div class="table-responsive">
			<table class="table table-striped" align="center">
				<thead>
					<tr>
						<th>Remote Name</th>
					</tr>	
				</thead>
				<tbody>
					{% for remote in remotes %}
					<tbody>
						<tr>
							<td>
								<a href="{% url 'television:remote-detail' slug=remote.slug %}">{{ remote }}</a>
							</td>
						</tr>
					</tbody>
					{% endfor %}
				</tbody>
			</table>
		</div>
	{% else %}
		<div>No remotes in your account. Start adding remotes now!</div>
	{% endif %}
{% endblock %}

television/templates/television/messages.html
{% for message in messages %}
	<div class="alert {{ message.tags }} alert dismissible" role="alert">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		{{message}}
	</div>
{% endfor %}

television/templates/television/remote_area.html
{% extends 'television/base.html' %}

{% block title %}Television Module{% endblock %}

{% block content_title %}{{ remote }}{% endblock %}

{% block voiceRecognizer %}onload="startConverting()"{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'television:index' %}">Television</a>
    &rsaquo; <a href="{% url 'television:brands' %}">Brands</a>
    &rsaquo; <a href="{% url 'television:remote-models' slug=remote.brand.slug %}">{{ remote.brand.name }} Remote Models</a>
    &rsaquo; <a href="{% url 'television:remote-detail' slug=remote.slug %}">{{ remote.model }}</a>
    &rsaquo; <a href="{% url 'television:remote-area' slug=remote.slug %}">Operate</a>
{% endblock %}

{% block content %}
	{% include 'television/messages.html' %}
	<div class="container">
	  <div class="remote-body">
	    <div class="remote-screen">
	      <div id="remote-typed"></div>
	    </div>
	    <div class="remote-button-row">
	      <div class="button c" onclick="buttonClickedremote('POWER','{{remote.slug}}')">ON</div>
	      <div class="button" onclick="buttonClickedremote('0','{{remote.slug}}')">0</div>
	      <div class="button l" onclick="buttonClickedremote('MUTE','{{remote.slug}}')"><span class="glyphicon glyphicon-volume-off"></span></div>
	      <div class="button l" onclick="buttonClickedremote('CH+','{{remote.slug}}')">Ch+</div>
	    </div>
	    <div class="remote-button-row">
	      <div class="button" onclick="buttonClickedremote('1','{{remote.slug}}')">1</div>
	      <div class="button" onclick="buttonClickedremote('2','{{remote.slug}}')">2</div>
	      <div class="button" onclick="buttonClickedremote('3','{{remote.slug}}')">3</div>
	      <div class="button l" onclick="buttonClickedremote('CH-','{{remote.slug}}')">Ch-</div>
	    </div>
	    <div class="remote-button-row">
	      <div class="button" onclick="buttonClickedremote('4','{{remote.slug}}')">4</div>
	      <div class="button" onclick="buttonClickedremote('5','{{remote.slug}}')">5</div>
	      <div class="button" onclick="buttonClickedremote('6','{{remote.slug}}')">6</div>
	      <div class="button l" onclick="buttonClickedremote('VOL+','{{remote.slug}}')">Vol+</div>
	    </div>
	    <div class="remote-button-row">
	      <div class="button" onclick="buttonClickedremote('7','{{remote.slug}}')">7</div>
	      <div class="button" onclick="buttonClickedremote('8','{{remote.slug}}')">8</div>
	      <div class="button" onclick="buttonClickedremote('9','{{remote.slug}}')">9</div>
	      <div class="button l" onclick="buttonClickedremote('VOL-','{{remote.slug}}')">Vol-</div>
	    </div>
	  </div>
	</div>
{% endblock %}

television/templates/television/remote_detail.html
{% extends 'television/base.html' %}

{% block title %}Television Module{% endblock %}

{% block content_title %}{{ remote }}{% endblock %}

{% block voiceRecognizer %}onload="startConverting()"{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'television:index' %}">Television</a>
    &rsaquo; <a href="{% url 'television:brands' %}">Brands</a>
    &rsaquo; <a href="{% url 'television:remote-models' slug=remote.brand.slug %}">{{ remote.brand.name }} Remote Models</a>
    &rsaquo; <a href="{% url 'television:remote-detail' slug=remote.slug %}">{{ remote.model }}</a>
{% endblock %}

{% block content %}
	{% include 'television/messages.html' %}
	<div class="table-responsive">
		<table class="table table-striped" align="center">
			<thead>
				<tr>
					<th>Remote information</th>
				</tr>
			</thead>	
			<tbody>
				<tr>
					<th>Brand: </th><td>{{ remote.brand }}</td>
				</tr>
				<tr>
					<th>Model: </th><td>{{ remote.model }}</td>
				</tr>
				<tr>
					<th>Description: </th><td>{{ remote.description }}</td>
				</tr>
				<tr>
					<th>Compatible: </th><td>{{ remote.get_remote_type_display|title }}</td>
				</tr>
			</tbody>
		</table>
	</div>
	{% if flag %}
		<div class="text-center">
			<a href="{% url 'television:remote-area' slug=remote.slug %}"><button class="btn btn-info"><span class="glyphicon glyphicon-menu-right"></span>&nbsp; Use remote</button></a>
		</div>
	{% else %}
		<div class="text-center">
			<a href="{% url 'television:remote-add' slug=remote.slug %}"><button class="btn btn-success"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Add remote to my account</button></a>
		</div>
	{% endif %}
{% endblock %}

television/templates/television/remote_models.html
{% extends 'television/base.html' %}

{% block title %}Television Module{% endblock %}

{% block content_title %}Available {{ brand.name }} Remotes{% endblock %}

{% block voiceRecognizer %}onload="startConverting()"{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'television:index' %}">Television</a>
    &rsaquo; <a href="{% url 'television:brands' %}">Brands</a>
    &rsaquo; <a href="{% url 'television:remote-models' slug=brand.slug %}">{{ brand.name }} Remote Models</a>
{% endblock %}

{% block content %}
	{% include 'television/messages.html' %}
	<div class="table-responsive">
		<table class="table table-striped" align="center">
			<thead>
				<tr>
					<th>Remote Name</th>
				</tr>	
			</thead>
			<tbody>
				{% for model in models %}
				<tbody>
					<tr>
						<td>
							<a href="{% url 'television:remote-detail' slug=model.slug %}">{{ model }}</a>
						</td>
					</tr>
				</tbody>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}