homemaker/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from accounts.views import landing_page, home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', landing_page, name='landing-page'),
    url(r'^home/$', home, name='home'),
    url(r'^audiosystem/', include('audiosystem.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^mobile/', include('mobile.urls')),
    url(r'^television/', include('television.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mobile/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'mobile'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^contacts/$', views.contact_list, name='all-contacts'),
	url(r'^contacts/(?P<slug>[\w-]+)/$', views.custom_contact_list, name='custom-contacts'),
	url(r'^contact/add/$', views.add_contact, name='add-contact'),
	url(r'^contact/edit/(?P<slug>[\w-]+)/$', views.edit_contact, name='edit-contact'),
	url(r'^contact/delete/(?P<slug>[\w-]+)/$', views.DeleteContact.as_view(), name='delete-contact'),
	url(r'^contact/(?P<slug>[\w-]+)/$', views.contact_detail, name="contact"),
	url(r'^call/select-contact/$', views.call_select_contact, name="call-select-contact"),
	url(r'^call/(?P<slug>[\w-]+)/$', views.call, name="call"),
	url(r'^check-incoming-call-sms/$', views.incoming_call_sms_check, name='check-incoming-call-sms'),
	url(r'^receive_call/$', views.receive_call, name='receive-call'),
	url(r'^abort_call/$', views.abort_call, name='abort-call'),
	url(r'^check_call_connection/$', views.check_call_connection, name='check-call-connection'),
	url(r'^message/select-contact/$', views.message_select_contact, name="message-select-contact"),
	url(r'^message/(?P<slug>[\w-]+)/$', views.chatroom, name="message"),
	url(r'^send_sms/$', views.send_sms_ajax, name="send-sms"),
	url(r'^make-call/$', views.make_call, name='make-call'),
]

mobile/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import FileExtensionValidator
from django.utils import timezone
import datetime

# Create your models here.

class Contact(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	name = models.CharField(max_length=50, default='')
	original_name = models.CharField(max_length=50, default='')
	avatar = models.FileField(null=True, default='default_avatar.png', help_text="upload jpg, jpeg, png files only", validators=[FileExtensionValidator(['jpg','png','jpeg'])])
	phone_number = models.CharField(max_length=13, default='', unique=False)
	unknown = models.BooleanField(default=False)
	slug = models.SlugField(unique=True, max_length=500)

	def get_absolute_url(self):
		return reverse('mobile:contact-detail')

	def __str__(self):
		return self.name + " " + self.phone_number

class Message(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	to_contact = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name='%(class)s_to_contact')
	from_contact = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name='%(class)s_from_contact',blank=True,null=True)
	text = models.CharField(max_length=2000,blank=True,null=True)
	sent_datetime = models.DateTimeField(default=timezone.now)	#status - sending
	delivered_datetime = models.DateTimeField(default=timezone.now)	#status - delivered
	received_datetime = models.DateTimeField(default=timezone.now)
	is_incoming = models.BooleanField(default=False)
	is_outgoing = models.BooleanField(default=True)
	is_replied = models.BooleanField(default=False)
	unknown_contact = models.BooleanField(default=True)
	unknown_mobile = models.CharField(max_length=13, default='', unique=False,blank=True)
	STATUS_CHOICES = (
		('s', 'sending'),
		('d', 'delivered'),		#equivalent to sent and if delivered then status is successful
		('r', 'received'),
		('f', 'fail'),
	)
	status = models.CharField(max_length=1, default='s', choices=STATUS_CHOICES, blank=False, null=True)
	def __str__(self):
		return str(self.to_contact)

class Call(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	to_contact = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name='%(class)s_to_contact')
	from_contact = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name='%(class)s_from_contact',blank=True,null=True)
	called_datetime = models.DateTimeField(default=timezone.now)
	received_datetime = models.DateTimeField(default=timezone.now)
	aborted_datetime = models.DateTimeField(default=timezone.now)
	duration = models.CharField(max_length=15,blank=True,null=True)
	is_outgoing = models.BooleanField(default=True)
	is_incoming = models.BooleanField(default=False)
	is_missed_call = models.BooleanField(default=True)
	is_received = models.BooleanField(default=False)
	unknown_contact = models.BooleanField(default=True)
	STATUS_CHOICES = (
		('c', 'calling'),
		('r', 'received'),
		('o', 'ongoing'),
		('h', 'hold'),
		('a', 'aborted'),
		('s', 'success'),
		('f', 'fail'),
	)
	status = models.CharField(max_length=1, default='c', choices=STATUS_CHOICES, blank=False, null=True)

	def __str__(self):
		return str(self.to_contact) + str(self.from_contact)

mobile/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core import validators
from .models import Contact, Message

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = ['name', 'phone_number', 'avatar']

class MessageForm(forms.ModelForm):
	class Meta:
		model = Message
		fields = ['text',]
		widgets = {'text':forms.TextInput(attrs={'class':'form-control','rows':5,})}

mobile/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.utils.text import slugify
from django.utils import timezone
from django.db.models import Q
from .models import Contact, Message
from accounts.models import RPiUser
from .forms import ContactForm, MessageForm
from .scripts import call_sms_functions

# Create your views here.

@login_required
def index(request):
	profile = get_object_or_404(RPiUser, user=request.user)
	return render(request, 'mobile/index.html', {'profile':profile})

@login_required
def contact_list(request):
	contacts = Contact.objects.filter(Q(user=request.user) & (~Q(slug=str(request.user)+'RPiDefaultUser')) & Q(unknown=False))
	return render(request, 'mobile/contacts.html', {'contacts':contacts})

@login_required
def custom_contact_list(request,slug):
	contacts = Contact.objects.filter(Q(user=request.user)&Q(original_name=slug)&(~Q(slug=str(request.user)+'RPiDefaultUser')) & Q(unknown=False))
	return render(request, 'mobile/contacts.html', {'contacts':contacts})

@login_required
def contact_detail(request,slug):
	contact = get_object_or_404(Contact, slug=slug)
	return render(request, 'mobile/contact_detail.html', {'contact':contact})

@login_required
def add_contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST, request.FILES)
		if form.is_valid():
			new_form = form.save(commit=False)
			new_contact = Contact.objects.create(user = request.user)
			new_contact.original_name = form.cleaned_data['name'].lower()
			try:
				contact_name = Contact.objects.filter(user=request.user, original_name=new_contact.original_name)
				print(contact_name)
				no_contacts = contact_name.count()
				print(no_contacts)
				if no_contacts>0:
					new_contact.name = new_contact.original_name + str(no_contacts)
				else:
					new_contact.name = new_contact.original_name	
			except Contact.DoesNotExist:
				new_contact.name = new_contact.original_name
			new_contact.slug = slugify(new_contact.name+str(request.user))
			new_contact.phone_number = form.cleaned_data['phone_number']
			new_contact.avatar = form.cleaned_data['avatar']
			new_contact.save()
			return redirect('mobile:contact', slug=new_contact.slug)
	else:
		form = ContactForm()
	return render(request, 'mobile/add_contact.html', {'form':form})

@login_required
def edit_contact(request, slug):
	contact = get_object_or_404(Contact, slug=slug)
	if request.method == 'POST':
		form = ContactForm(request.POST, request.FILES, instance=contact)
		if form.is_valid():
			new_form = form.save(commit=False)
			if contact.original_name != form.cleaned_data['name'].lower():
				contact.original_name = form.cleaned_data['name'].lower()
				try:
					contact_name = Contact.objects.filter(user=request.user, original_name=contact.original_name)
					print(contact_name)
					no_contacts = contact_name.count()
					print(no_contacts)
					if no_contacts>0:
						contact.name = contact.original_name + str(no_contacts)
					else:
						contact.name = contact.original_name
				except Contact.DoesNotExist:
					contact.name = contact.original_name
				contact.slug = slugify(contact.name+str(request.user))
			form.save()
			contact.save()
			return redirect('mobile:contact', slug=contact.slug)
		else:
			messages.error(request, "Error processing form. Please fill the correct details")
	else:
		form = ContactForm(instance=contact)
	return render(request, 'mobile/edit_contact.html', {'form':form,'contact':contact})

@method_decorator(login_required, name='dispatch')
class DeleteContact(DeleteView):
    model = Contact
    template_name = 'mobile/contact_confirm_delete.html'
    success_url = reverse_lazy('mobile:all-contacts')

@login_required
def call_select_contact(request):
	contacts = Contact.objects.filter(Q(user=request.user) & (~Q(slug=str(request.user)+'RPiDefaultUser')) & Q(unknown=False))
	return render(request, 'mobile/call_select_contact.html', {'contacts':contacts})

@login_required
def call(request, slug):
	contact = get_object_or_404(Contact, slug=slug)
	return render(request, 'mobile/call.html', {'contact':contact})

@login_required
def message_select_contact(request):
	contacts = Contact.objects.filter(Q(user=request.user) & (~Q(slug=str(request.user)+'RPiDefaultUser')) & Q(unknown=False))
	return render(request, 'mobile/message_select_contact.html', {'contacts':contacts})

@login_required
def chatroom(request,slug):
	contact = get_object_or_404(Contact, slug=slug)
	messages = Message.objects.filter(Q(user=request.user) & (Q(to_contact=contact) | Q(from_contact=contact)))
	form = MessageForm()
	return render(request, 'mobile/chatroom.html', {'contact':contact, 'messages':messages, 'form':form})

@login_required
def send_sms_ajax(request):
	if request.method == 'POST':
		if request.is_ajax():
			phone_number = request.POST.get('phone_number')
			text = request.POST.get('text')
			print(phone_number,text)
			flag = call_sms_functions.send_sms(request.user,phone_number,text)
			print(flag)
			if flag:
				success=True
			else:
				success = False
	return JsonResponse({
	    'success': success,
	})

@login_required
def message(request,slug):
	contact = get_object_or_404(Contact, slug=slug)

@login_required
def incoming_call_sms_check(request):
	call_sms_coming = call_sms_functions.incoming_call_sms(request.user)
	if call_sms_coming:
		call_sms_coming = call_sms_coming.split(";")
		message_coming = False
		call_coming = False
		contact_in_phonebook = False
		contact_name = ''
		contact_photo = ''
		contact_number = ''
		smsSlug=''
		if call_sms_coming[0]=="CALL":
			contact_number = call_sms_coming[1]
			incoming_number = contact_number[3:]
			try:
				contact_details = Contact.objects.get(user=request.user, phone_number=incoming_number)
				call_coming = True
				message_coming = False
				contact_in_phonebook = True
				contact_name = contact_details.name
				contact_number = contact_details.phone_number
				contact_photo = contact_details.avatar.url
			except Contact.DoesNotExist:
				call_coming = True
				message_coming = False
		elif call_sms_coming[0]=="MESSAGE":
			message_coming = True
			call_coming = False
			new_message_id = call_sms_coming[1]
			new_message = get_object_or_404(Message,id=new_message_id)
			contact_in_phonebook = not new_message.unknown_contact
			if contact_in_phonebook:
				contact_number = new_message.from_contact.phone_number
				contact_name = new_message.from_contact.name
				contact_photo = new_message.from_contact.avatar.url
				contact_details = Contact.objects.get(user=request.user, phone_number=contact_number)
				smsSlug = contact_details.slug
			else:
				uk_contact_details = Contact.objects.get(user=request.user, phone_number=contact_number,unknown=True)
				contact_name = new_message.from_contact.name
				smsSlug = uk_contact_details.slug
		return JsonResponse({
			'call_coming': call_coming,
			'message_coming':message_coming,
			'contact_in_phonebook': contact_in_phonebook,
			'contact_name': contact_name,
			'contact_number': contact_number,
			'contact_photo': contact_photo,
			'smsSlug': smsSlug,
		})
	else:
		return JsonResponse({
			'call_coming':False
			})

@login_required
def receive_call(request):
	flag = call_sms_functions.receive_call()
	return JsonResponse({
		'success':flag
	})

@login_required
def make_call(request):
	if request.method == 'POST':
		if request.is_ajax():
			phone_number = request.POST.get('phone_number')
			call_going = call_sms_functions.make_call(phone_number)
			if call_going:
				contact_in_phonebook = False
				contact_name = ''
				contact_photo = ''
				contact_number = ''
				try:
					contact_details = Contact.objects.get(user=request.user, phone_number=phone_number)
					contact_in_phonebook = True
					contact_name = contact_details.name
					contact_number = contact_details.phone_number
					contact_photo = contact_details.avatar.url
				except Contact.DoesNotExist:
					pass
				return JsonResponse({
					'call_going':call_going,
					'contact_in_phonebook': contact_in_phonebook,
					'contact_name': contact_name,
					'contact_number': contact_number,
					'contact_photo': contact_photo,
				})
			else:
				return JsonResponse({
					'call_going':call_going
					})

@login_required
def abort_call(request):
	flag = call_sms_functions.abort_call()
	return JsonResponse({
		'success':flag
	})

@login_required
def check_call_connection(request):
	flag = call_sms_functions.check_call_connection()
	connected = False
	if flag:
		connected = False
	else:
		connected = True
	return JsonResponse({
		'connected':connected
	})

mobile/templates/mobile/add_contact.html
{% extends 'mobile/base.html' %}

{% block title %}New Contact{% endblock %}

{% block content_title %}New Contact{% endblock %}

{% block voiceRecognizer %}onload="startConvertingFormData()"{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'mobile:index' %}">Mobile</a>
    &rsaquo; <a href="{% url 'mobile:all-contacts' %}">Contacts</a>
	&rsaquo; Add contact</a>
{% endblock %}


{% block content %}
	{% include 'mobile/messages.html' %}
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% include 'mobile/form_template.html' %}
		<button type="submit" class="btn btn-success quarterWidth" id="submitBtn"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Add Contact</button>
	</form>
{% endblock %}

mobile/templates/mobile/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
                
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Merienda+One|Montserrat|PT+Sans|Sanchez" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'mobile/css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'audiosystem/css/audiobox.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'mobile/css/forms.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'mobile/css/keyboard.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'mobile/css/callModal.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'mobile/css/smsModal.css' %}">
        {% block extrahead %}{% endblock %}
    </head>

    <body {% block voiceRecognizer %}{% endblock %}>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">Homemaker Assistance System</a>
                </div>

                <div class="collapse navbar-collapse" id="navBar">
                    <ul class="nav navbar-nav">
                        <li><i class="fa fa-microphone fa-3x menuMicorphone"></i></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="">Demo</a></li>
                        <li><a href="">Help</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block breadcrumbs %}
            <div class="breadcrumbs">
                <a href="{% url 'home' %}">Home</a>
                {% block crumbs %}
                {% endblock %}
            </div>
        {% endblock %}

        <div id="callModal" class="modal">
            {% include 'mobile/call_modal.html' %}
        </div>

        <div id="smsModal" class="modal">
            {% include 'mobile/sms_modal.html' %}
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="panel">
                    <div class="panel-heading">      
                        <h3 class="text-center">{% block content_title %}{% endblock %}</h3>
                        <hr>
                    </div>
                    <div class="panel-body">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>

        <footer class="container-fluid">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-xs-12 footerMenu">
                        <h4 class="text-center"><b>Links</b></h4>
                        <ul>
                            <li>
                                <a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span>&nbsp; Home</a>
                            </li>
                            <li>
                                <a href="{% url 'mobile:call-select-contact' %}"><span class="glyphicon glyphicon-earphone"></span>&nbsp; Call</a>
                            </li>
                            <li>
                                <a href="{% url 'mobile:message-select-contact' %}"><i class="fa fa-comments" aria-hidden="true"></i>&nbsp; Message</a>
                            </li>
                        </ul>
                    </div>
                </div>  
            </div>
        </footer>
        <script type="text/javascript" src="{% static 'audiosystem/js/tts.js' %}"></script>
        <script type="text/javascript" src="{% static 'audiosystem/js/ttsForm.js' %}"></script>
        <script type="text/javascript" src="{% static 'audiosystem/js/select_contacts.js' %}"></script>
        <script type="text/javascript" src="{% static 'audiosystem/js/confirmations.js' %}"></script>
        <script type="text/javascript" src="{% static 'mobile/js/keyboard.js' %}"></script>
        <script type="text/javascript" src="{% static 'mobile/js/call_sms.js' %}"></script>
        <script type="text/javascript">
            function call_voice(){
                check_incoming_call_sms();
                startConverting();
                console.log("functions loaded");
            }
        </script>
    </body>
</html>

mobile/templates/mobile/call.html
{% extends 'mobile/base.html' %}

{% block title %}Calling{% endblock %}

{% block content_title %}Calling {{ contact.name }}{% endblock %}

{% block voiceRecognizer %}onload="call_voice()"{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'mobile:index' %}">Mobile</a>
    &rsaquo; <a href="{% url 'mobile:call-select-contact' %}">Call</a>
{% endblock %}

{% block content %}
	{% include 'mobile/messages.html' %}
	<div class="text-center">
		<span class="glyphicon glyphicon-earphone" style="font-size: 100pt;"></span>
	</div>
{% endblock %}

mobile/templates/mobile/contact_detail.html
{% extends 'mobile/base.html' %}

{% block title %}{{ contact.name }}{% endblock %}

{% block content_title %}{{ contact.name }}{% endblock %}

{% block voiceRecognizer %}onload="startConvertingFormData()"{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'mobile:index' %}">Mobile</a>
    &rsaquo; <a href="{% url 'mobile:all-contacts' %}">Contacts</a>
    &rsaquo; <a href="{% url 'mobile:contact' slug=contact.slug %}">{{ contact.name }}</a>
{% endblock %}

{% block content %}
	{% include 'mobile/messages.html' %}
	<div class="text-center">
		<img src="{{ contact.avatar.url }}" alt="{{ contact.name }}" title="{{ contact.name }}" height="100px" class="avatar" />
	</div>
	<div class="table-responsive text-center">
		<table class="table">
			<tr>
				<td>Name</td>
				<td>{{ contact.original_name }}</td>
			</tr>
			<tr>
				<td>Phone number</td>
				<td>{{ contact.phone_number }}</td>
			</tr>
		</table>
	</div>
	<div class="text-center">
		<a href="{% url 'mobile:message' slug=contact.slug %}"><button class="btn btn-primary quarterWidth"><i class="fa fa-comments" aria-hidden="true"></i>&nbsp; Message</button></a>
		<a href="#" onclick="make_call_number('{{ contact.phone_number }}')"><button class="btn btn-success quarterWidth"><span class="glyphicon glyphicon-earphone"></span>&nbsp; Call</button></a>
		<a href="{% url 'mobile:edit-contact' contact.slug %}"><button class="btn btn-info quarterWidth"><span class="glyphicon glyphicon-pencil"></span>&nbsp; Edit Contact</button></a>	
		<form action="{% url 'mobile:delete-contact' contact.slug %}" method="get">
			{% csrf_token %}
			<input type="hidden" name="contact_id" value="{{ contactID }}">
			<button type="submit" class="btn btn-danger quarterWidth" id="deleteBtn"><span class="glyphicon glyphicon-trash"></span>&nbsp;Delete</button>
		</form>
	</div>
{% endblock %}

mobile/templates/mobile/contacts.html
{% extends 'mobile/base.html' %}

{% block title %}Contacts{% endblock %}

{% block content_title %}Contacts{% endblock %}

{% block voiceRecognizer %}onload="selectContacts()"{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'mobile:index' %}">Mobile</a>
    &rsaquo; <a href="{% url 'mobile:all-contacts' %}">Contacts</a>
{% endblock %}

{% block content %}
	{% include 'mobile/messages.html' %}
		<form class="navbar-form text-center" role="search" method="get" action="">
			<div class="form-group">
				<input type="text" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Search contacts" />
			</div>
			<button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
		</form>
		<div class="addContact text-center">
			<a href="{% url 'mobile:add-contact' %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Add Contact</button></a>
		</div>
		<div class="table-responsive">
			<table class="table table-striped" align="center">
				<thead>
					<tr>
						<th>Name</th>
						<th>Phone Number</th>
						<th>Call</th>
						<th>Message</th>
					</tr>
				</thead>
				<tbody>
					{% for contact in contacts %}
					<tbody>
						<tr>
							<td>
								<img src="{{ contact.avatar.url }}" alt="{{ contact.name }}" title="{{ contact.name }}" height="20px" />
								<a href="{% url 'mobile:contact' slug=contact.slug %}" class="selectContact">{{ contact.name }}</a>
							</td>
							<td>{{ contact.phone_number }}</td>
							<td><a href="{% url 'mobile:call' slug=contact.slug %}"><button class="btn btn-success btn-xs"><span class="glyphicon glyphicon-earphone"></span></button></a></td>
							<td><a href="{% url 'mobile:message' slug=contact.slug %}"><button class="btn btn-primary btn-xs"><i class="fa fa-comments" aria-hidden="true"></i></button></a></td>
						</tr>
					</tbody>
					{% endfor %}
				</tbody>
			</table>
		</div>
{% endblock %}

mobile/templates/mobile/index.html
{% extends 'mobile/base.html' %}

{% block title %}Mobile Module{% endblock %}

{% block content_title %}Mobile - {{ profile.mobile_no }}{% endblock %}

{% block voiceRecognizer %}onload="call_voice()"{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'mobile:index' %}">Mobile</a>
{% endblock %}

{% block content %}
	<div class="col-sm-4 col-md-4 col-xs-4 text-center">
		<a href="{% url 'mobile:call-select-contact' %}"><button class="btn btn-success"><span class="glyphicon glyphicon-earphone"></span>&nbsp; Call</button></a>
	</div>
	<div class="col-sm-4 col-md-4 col-xs-4 text-center">
		<a href="{% url 'mobile:message-select-contact' %}"><button class="btn btn-primary"><i class="fa fa-comments" aria-hidden="true"></i>&nbsp; Message</button></a>
	</div>
	<div class="col-sm-4 col-md-4 col-xs-4 text-center">
		<a href="{% url 'mobile:all-contacts' %}"><button class="btn btn-info"><i class="fa fa-address-book" aria-hidden="true"></i>&nbsp; Contacts</button></a>
	</div>
{% endblock %}

mobile/templates/mobile/message.html
{% extends 'mobile/base.html' %}

{% block title %}Message{% endblock %}

{% block content_title %}Message {{ contact.name }}{% endblock %}

{% block crumbs %}
    &rsaquo; <a href="{% url 'mobile:index' %}">Mobile</a>
    &rsaquo; <a href="{% url 'mobile:message-select-contact' %}">Message</a>
{% endblock %}

{% block content %}
	{% include 'mobile/messages.html' %}
	<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div>
			{% include 'mobile/form_template.html' %}
			<div class="submit-row" style="text-align: left;">
				<button type="submit" class="btn btn-success">Send Message</button>
			</div>
		</div>	
	</form>
{% endblock %}